### ISSUE TITLE
Confusing CSS

### ISSUE THREAD

**Issue by greg-raven** [neocities/element#4]
There seem to be several issues with element.css. There are many duplicate definitions, some of which are identical and some of which are different. You also preface elements with the .element class, which seems unnecessary, and in any case is not recommended practice. There is also a conflict between the vertical align and display attribute in one of your input definitions. Finally, the box model is not supported by IE6 or IE7, which may be by design but probably should be called out explicitly. Many of these issues can be seen by pasting the code into https://csscomb.herokuapp.com/online

**Comment by kyledrake** [comment]
Thanks for the feedback. I've cleaned up things a little bit (but not completely), moved from class=element to root as you suggested. IE6/7 support indeed is not a priority so won't be fixing that.

There's a few more things you mentioned that are indeed picked up by the linter, I'm walking away for now but there certainly could be further improvements and I hope to get to that in the future.

Thanks again for the feedback!
